FROM cockroachdb/cockroach:v21.1.7

# RUN cockroach start --insecure --join=cockroach1,cockroach2,cockroach3 --background

# RUN microdnf install bind-utils jq python3-pip \
#     && pip3 install pgcli